#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Tianling Shen <cnsztl@immortalwrt.org>

USE_PROCD=1
START=99

CONF="dae"
PROG="/usr/bin/dae"
LOG="/var/log/dae/dae.log"

setlocaluse() {
  uci set dhcp.@dnsmasq[0].localuse="1"
  uci commit dhcp
  /etc/init.d/dnsmasq restart
}

dellocaluse() {
  uci set dhcp.@dnsmasq[0].localuse="0"
  uci commit dhcp
  /etc/init.d/dnsmasq restart
  . /lib/functions/network.sh
  network_find_wan LOGICAL_WAN || exit 1
  dns_list=$(ubus call network.interface.$LOGICAL_WAN status | jsonfilter -e '@["dns-server"]' | sed 's/[]["]//g' | sed 's/,/\n/g' | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b')
  [ -z "$dns_list" ] && dns_list="119.29.29.29 180.76.76.76 223.5.5.5"
  grep -v '^nameserver ' /etc/resolv.conf > /tmp/resolv.conf.new.dae 2>/dev/null
  for dns in $dns_list; do
    echo "nameserver $dns" >> /tmp/resolv.conf.new.dae
  done
  cat /tmp/resolv.conf.new.dae > /etc/resolv.conf
  rm -f /tmp/resolv.conf.new.dae
}


start_service() {
	config_load "$CONF"

	local enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1
	dellocaluse

	local config_file
	config_get config_file "config" "config_file" "/etc/dae/config.dae"

	"$PROG" validate -c "$config_file" || return 1

	procd_open_instance "$CONF"
	procd_set_param env QUIC_GO_ENABLE_GSO=true
	procd_set_param env DAE_LOCATION_ASSET="/usr/share/v2ray"
	procd_set_param command "$PROG"
	procd_append_param command run -c "$config_file"
	procd_append_param command --logfile "$LOG"
	procd_append_param command --logfile-maxsize "5"

	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param respawn
	# procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}

stop_service() {
  setlocaluse
}

reload_service() {
	stop
	sleep 1
	start
}
